import { isArtifactCodeContent } from "@/lib/artifact_content_types";
import { BaseStore, LangGraphRunnableConfig } from "@langchain/langgraph";
import { ArtifactCodeV3, ArtifactMarkdownV3, Reflections } from "../types";
import { ChatAnthropic } from "@langchain/anthropic";
import { ChatOpenAI } from "@langchain/openai";
import { ChatFireworks } from "@langchain/community/chat_models/fireworks";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";

export const formatReflections = (
  reflections: Reflections,
  extra?: {
    /**
     * Will only include the style guidelines in the output.
     * If this is set to true, you may not specify `onlyContent` as `true`.
     */
    onlyStyle?: boolean;
    /**
     * Will only include the content in the output.
     * If this is set to true, you may not specify `onlyStyle` as `true`.
     */
    onlyContent?: boolean;
  }
): string => {
  if (extra?.onlyStyle && extra?.onlyContent) {
    throw new Error(
      "Cannot specify both `onlyStyle` and `onlyContent` as true."
    );
  }

  let styleRulesArr = reflections.styleRules;
  let styleRulesStr = "No style guidelines found.";
  if (!Array.isArray(styleRulesArr)) {
    try {
      styleRulesArr = JSON.parse(styleRulesArr);
      styleRulesStr = styleRulesArr.join("\n- ");
    } catch (_) {
      console.error(
        "FAILED TO PARSE STYLE RULES. \n\ntypeof:",
        typeof styleRulesArr,
        "\n\nstyleRules:",
        styleRulesArr
      );
    }
  }

  let contentRulesArr = reflections.content;
  let contentRulesStr = "No memories/facts found.";
  if (!Array.isArray(contentRulesArr)) {
    try {
      contentRulesArr = JSON.parse(contentRulesArr);
      contentRulesStr = contentRulesArr.join("\n- ");
    } catch (_) {
      console.error(
        "FAILED TO PARSE CONTENT RULES. \n\ntypeof:",
        typeof contentRulesArr,
        "\ncontentRules:",
        contentRulesArr
      );
    }
  }

  const styleString = `The following is a list of style guidelines previously generated by you:
<style-guidelines>
- ${styleRulesStr}
</style-guidelines>`;
  const contentString = `The following is a list of memories/facts you previously generated about the user:
<user-facts>
- ${contentRulesStr}
</user-facts>`;

  if (extra?.onlyStyle) {
    return styleString;
  }
  if (extra?.onlyContent) {
    return contentString;
  }

  return styleString + "\n\n" + contentString;
};

export const ensureStoreInConfig = (
  config: LangGraphRunnableConfig
): BaseStore => {
  if (!config.store) {
    throw new Error("`store` not found in config");
  }
  return config.store;
};

export const formatArtifactContent = (
  content: ArtifactMarkdownV3 | ArtifactCodeV3,
  shortenContent?: boolean
): string => {
  let artifactContent: string;

  if (isArtifactCodeContent(content)) {
    artifactContent = shortenContent
      ? content.code?.slice(0, 500)
      : content.code;
  } else {
    artifactContent = shortenContent
      ? content.fullMarkdown?.slice(0, 500)
      : content.fullMarkdown;
  }
  return `Title: ${content.title}\nArtifact type: ${content.type}\nContent: ${artifactContent}`;
};

export const formatArtifactContentWithTemplate = (
  template: string,
  content: ArtifactMarkdownV3 | ArtifactCodeV3,
  shortenContent?: boolean
): string => {
  return template.replace(
    "{artifact}",
    formatArtifactContent(content, shortenContent)
  );
};

export const getModelNameAndProviderFromConfig = (
  config: LangGraphRunnableConfig
): { modelName: string; modelProvider: string } => {
  const customModelName = config.configurable?.customModelName as string;
  if (!customModelName) {
    throw new Error("Model name is missing in config.");
  }
  if (customModelName.includes("gpt-")) {
    return {
      modelName: customModelName,
      modelProvider: "openai",
    };
  }
  if (customModelName.includes("claude-")) {
    return {
      modelName: customModelName,
      modelProvider: "anthropic",
    };
  }
  if (customModelName.includes("fireworks/")) {
    return {
      modelName: customModelName,
      modelProvider: "fireworks",
    };
  }
  if (customModelName.includes("gemini-")) {
    return {
      modelName: customModelName,
      modelProvider: "google-genai",
    };
  }

  throw new Error("Unknown model provider");
};

export const initChatModelWithConfig = async (
  modelName: string,
  config: {
    temperature?: number;
    maxTokens?: number;
    modelProvider: string;
  }
) => {
  switch (config.modelProvider) {
    case "openai":
      return new ChatOpenAI({
        modelName: modelName,
        temperature: config.temperature ?? 0,
        maxTokens: config.maxTokens,
        configuration: {
          baseURL: process.env.OPENAI_BASE_URL,
        },
      });
    case "anthropic":
      return new ChatAnthropic({
        modelName: modelName,
        temperature: config.temperature ?? 0,
        maxTokens: config.maxTokens,
        anthropicApiUrl: process.env.ANTHROPIC_BASE_URL,
      });
    case "google-genai":
      return new ChatGoogleGenerativeAI({
        modelName: modelName,
        temperature: config.temperature ?? 0,
        maxOutputTokens: config.maxTokens,
        apiKey: process.env.GOOGLE_API_KEY,
        baseUrl: process.env.GOOGLE_API_BASE_URL,
      });
    case "fireworks":
      return new ChatFireworks({
        modelName: modelName,
        temperature: config.temperature ?? 0,
        maxTokens: config.maxTokens,
        apiKey: process.env.FIREWORKS_API_KEY,
      });
    default:
      throw new Error(`Unknown model provider: ${config.modelProvider}`);
  }
};

export const initChatModel = async (
  modelName: string, 
  config: {
    temperature?: number;
    maxTokens?: number;
    modelProvider: string;
  }
) => {
  return initChatModelWithConfig(modelName, config);
};
